// Generated by swizzlegen. Do not edit.

use crate::{Vec2, Vec3, Vec4, XY, XYZ};

pub trait Vec2Swizzles {
    fn xxxx(self) -> Vec4;
    fn xxxy(self) -> Vec4;
    fn xxyx(self) -> Vec4;
    fn xxyy(self) -> Vec4;
    fn xyxx(self) -> Vec4;
    fn xyxy(self) -> Vec4;
    fn xyyx(self) -> Vec4;
    fn xyyy(self) -> Vec4;
    fn yxxx(self) -> Vec4;
    fn yxxy(self) -> Vec4;
    fn yxyx(self) -> Vec4;
    fn yxyy(self) -> Vec4;
    fn yyxx(self) -> Vec4;
    fn yyxy(self) -> Vec4;
    fn yyyx(self) -> Vec4;
    fn yyyy(self) -> Vec4;
    fn xxx(self) -> Vec3;
    fn xxy(self) -> Vec3;
    fn xyx(self) -> Vec3;
    fn xyy(self) -> Vec3;
    fn yxx(self) -> Vec3;
    fn yxy(self) -> Vec3;
    fn yyx(self) -> Vec3;
    fn yyy(self) -> Vec3;
    fn xx(self) -> Vec2;
    fn yx(self) -> Vec2;
    fn yy(self) -> Vec2;
}

impl Vec2Swizzles for Vec2 {
    #[inline]
    fn xxxx(self) -> Vec4 {
        Vec4::new(self.x, self.x, self.x, self.x)
    }
    #[inline]
    fn xxxy(self) -> Vec4 {
        Vec4::new(self.x, self.x, self.x, self.y)
    }
    #[inline]
    fn xxyx(self) -> Vec4 {
        Vec4::new(self.x, self.x, self.y, self.x)
    }
    #[inline]
    fn xxyy(self) -> Vec4 {
        Vec4::new(self.x, self.x, self.y, self.y)
    }
    #[inline]
    fn xyxx(self) -> Vec4 {
        Vec4::new(self.x, self.y, self.x, self.x)
    }
    #[inline]
    fn xyxy(self) -> Vec4 {
        Vec4::new(self.x, self.y, self.x, self.y)
    }
    #[inline]
    fn xyyx(self) -> Vec4 {
        Vec4::new(self.x, self.y, self.y, self.x)
    }
    #[inline]
    fn xyyy(self) -> Vec4 {
        Vec4::new(self.x, self.y, self.y, self.y)
    }
    #[inline]
    fn yxxx(self) -> Vec4 {
        Vec4::new(self.y, self.x, self.x, self.x)
    }
    #[inline]
    fn yxxy(self) -> Vec4 {
        Vec4::new(self.y, self.x, self.x, self.y)
    }
    #[inline]
    fn yxyx(self) -> Vec4 {
        Vec4::new(self.y, self.x, self.y, self.x)
    }
    #[inline]
    fn yxyy(self) -> Vec4 {
        Vec4::new(self.y, self.x, self.y, self.y)
    }
    #[inline]
    fn yyxx(self) -> Vec4 {
        Vec4::new(self.y, self.y, self.x, self.x)
    }
    #[inline]
    fn yyxy(self) -> Vec4 {
        Vec4::new(self.y, self.y, self.x, self.y)
    }
    #[inline]
    fn yyyx(self) -> Vec4 {
        Vec4::new(self.y, self.y, self.y, self.x)
    }
    #[inline]
    fn yyyy(self) -> Vec4 {
        Vec4::new(self.y, self.y, self.y, self.y)
    }
    #[inline]
    fn xxx(self) -> Vec3 {
        Vec3(XYZ {
            x: self.x,
            y: self.x,
            z: self.x,
        })
    }
    #[inline]
    fn xxy(self) -> Vec3 {
        Vec3(XYZ {
            x: self.x,
            y: self.x,
            z: self.y,
        })
    }
    #[inline]
    fn xyx(self) -> Vec3 {
        Vec3(XYZ {
            x: self.x,
            y: self.y,
            z: self.x,
        })
    }
    #[inline]
    fn xyy(self) -> Vec3 {
        Vec3(XYZ {
            x: self.x,
            y: self.y,
            z: self.y,
        })
    }
    #[inline]
    fn yxx(self) -> Vec3 {
        Vec3(XYZ {
            x: self.y,
            y: self.x,
            z: self.x,
        })
    }
    #[inline]
    fn yxy(self) -> Vec3 {
        Vec3(XYZ {
            x: self.y,
            y: self.x,
            z: self.y,
        })
    }
    #[inline]
    fn yyx(self) -> Vec3 {
        Vec3(XYZ {
            x: self.y,
            y: self.y,
            z: self.x,
        })
    }
    #[inline]
    fn yyy(self) -> Vec3 {
        Vec3(XYZ {
            x: self.y,
            y: self.y,
            z: self.y,
        })
    }
    #[inline]
    fn xx(self) -> Vec2 {
        Vec2(XY {
            x: self.x,
            y: self.x,
        })
    }
    #[inline]
    fn yx(self) -> Vec2 {
        Vec2(XY {
            x: self.y,
            y: self.x,
        })
    }
    #[inline]
    fn yy(self) -> Vec2 {
        Vec2(XY {
            x: self.y,
            y: self.y,
        })
    }
}
