[sse2_math]
features = "arbitrary approx bytemuck encase mint rand rkyv bytecheck serde speedy zerocopy debug-glam-assert"
exclude-files = [
    "tools/*",
    "src/neon.rs",
    "src/bool/neon/*",
    "src/f32/neon/*",
    "src/swizzles/neon/*",
    "src/wasm.rs",
    "src/bool/wasm/*",
    "src/f32/wasm/*",
    "src/swizzles/wasm/*",
    "benches/*",
    "tests/support.rs"
]

[scalar_math]
features = "scalar-math arbitrary approx bytemuck encase mint rand rkyv bytecheck serde speedy zerocopy debug-glam-assert"
exclude-files = [
    "tools/*",
    "src/neon.rs",
    "src/bool/neon/*",
    "src/f32/neon/*",
    "src/swizzles/neon/*",
    "src/wasm.rs",
    "src/bool/wasm/*",
    "src/f32/wasm/*",
    "src/swizzles/wasm/*",
    "benches/*",
    "tests/support.rs"
]

[core_simd]
features = "core-simd arbitrary approx bytemuck encase mint rand rkyv bytecheck serde speedy zerocopy debug-glam-assert"
exclude-files = [
    "tools/*",
    "src/neon.rs",
    "src/bool/neon/*",
    "src/f32/neon/*",
    "src/swizzles/neon/*",
    "src/wasm.rs",
    "src/bool/wasm/*",
    "src/f32/wasm/*",
    "src/swizzles/wasm/*",
    "benches/*",
    "tests/support.rs"
]
