// Generated by swizzles. Do not edit.

use super::{Vec2, Vec3, Vec4};

pub trait Vec2Swizzles {
    fn xxxx(self) -> Vec4;
    fn xxxy(self) -> Vec4;
    fn xxyx(self) -> Vec4;
    fn xxyy(self) -> Vec4;
    fn xyxx(self) -> Vec4;
    fn xyxy(self) -> Vec4;
    fn xyyx(self) -> Vec4;
    fn xyyy(self) -> Vec4;
    fn yxxx(self) -> Vec4;
    fn yxxy(self) -> Vec4;
    fn yxyx(self) -> Vec4;
    fn yxyy(self) -> Vec4;
    fn yyxx(self) -> Vec4;
    fn yyxy(self) -> Vec4;
    fn yyyx(self) -> Vec4;
    fn yyyy(self) -> Vec4;
    fn xxx(self) -> Vec3;
    fn xxy(self) -> Vec3;
    fn xyx(self) -> Vec3;
    fn xyy(self) -> Vec3;
    fn yxx(self) -> Vec3;
    fn yxy(self) -> Vec3;
    fn yyx(self) -> Vec3;
    fn yyy(self) -> Vec3;
    fn xx(self) -> Vec2;
    fn yx(self) -> Vec2;
    fn yy(self) -> Vec2;
}

impl Vec2Swizzles for Vec2 {
    #[inline]
    fn xxxx(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.0, self.0)
    }
    #[inline]
    fn xxxy(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.0, self.1)
    }
    #[inline]
    fn xxyx(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.1, self.0)
    }
    #[inline]
    fn xxyy(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.1, self.1)
    }
    #[inline]
    fn xyxx(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.0, self.0)
    }
    #[inline]
    fn xyxy(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.0, self.1)
    }
    #[inline]
    fn xyyx(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.1, self.0)
    }
    #[inline]
    fn xyyy(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.1, self.1)
    }
    #[inline]
    fn yxxx(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.0, self.0)
    }
    #[inline]
    fn yxxy(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.0, self.1)
    }
    #[inline]
    fn yxyx(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.1, self.0)
    }
    #[inline]
    fn yxyy(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.1, self.1)
    }
    #[inline]
    fn yyxx(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.0, self.0)
    }
    #[inline]
    fn yyxy(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.0, self.1)
    }
    #[inline]
    fn yyyx(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.1, self.0)
    }
    #[inline]
    fn yyyy(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.1, self.1)
    }
    #[inline]
    fn xxx(self) -> Vec3 {
        Vec3(self.0, self.0, self.0)
    }
    #[inline]
    fn xxy(self) -> Vec3 {
        Vec3(self.0, self.0, self.1)
    }
    #[inline]
    fn xyx(self) -> Vec3 {
        Vec3(self.0, self.1, self.0)
    }
    #[inline]
    fn xyy(self) -> Vec3 {
        Vec3(self.0, self.1, self.1)
    }
    #[inline]
    fn yxx(self) -> Vec3 {
        Vec3(self.1, self.0, self.0)
    }
    #[inline]
    fn yxy(self) -> Vec3 {
        Vec3(self.1, self.0, self.1)
    }
    #[inline]
    fn yyx(self) -> Vec3 {
        Vec3(self.1, self.1, self.0)
    }
    #[inline]
    fn yyy(self) -> Vec3 {
        Vec3(self.1, self.1, self.1)
    }
    #[inline]
    fn xx(self) -> Vec2 {
        Vec2(self.0, self.0)
    }
    #[inline]
    fn yx(self) -> Vec2 {
        Vec2(self.1, self.0)
    }
    #[inline]
    fn yy(self) -> Vec2 {
        Vec2(self.1, self.1)
    }
}
