// Generated by swizzles. Do not edit.

use super::{Vec2, Vec3, Vec4};

impl Vec3 {
    #[inline]
    pub fn xxxx(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.0, self.0)
    }

    #[inline]
    pub fn xxxy(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.0, self.1)
    }

    #[inline]
    pub fn xxxz(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.0, self.2)
    }

    #[inline]
    pub fn xxyx(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.1, self.0)
    }

    #[inline]
    pub fn xxyy(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.1, self.1)
    }

    #[inline]
    pub fn xxyz(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.1, self.2)
    }

    #[inline]
    pub fn xxzx(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.2, self.0)
    }

    #[inline]
    pub fn xxzy(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.2, self.1)
    }

    #[inline]
    pub fn xxzz(self) -> Vec4 {
        Vec4::new(self.0, self.0, self.2, self.2)
    }

    #[inline]
    pub fn xyxx(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.0, self.0)
    }

    #[inline]
    pub fn xyxy(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.0, self.1)
    }

    #[inline]
    pub fn xyxz(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.0, self.2)
    }

    #[inline]
    pub fn xyyx(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.1, self.0)
    }

    #[inline]
    pub fn xyyy(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.1, self.1)
    }

    #[inline]
    pub fn xyyz(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.1, self.2)
    }

    #[inline]
    pub fn xyzx(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.2, self.0)
    }

    #[inline]
    pub fn xyzy(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.2, self.1)
    }

    #[inline]
    pub fn xyzz(self) -> Vec4 {
        Vec4::new(self.0, self.1, self.2, self.2)
    }

    #[inline]
    pub fn xzxx(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.0, self.0)
    }

    #[inline]
    pub fn xzxy(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.0, self.1)
    }

    #[inline]
    pub fn xzxz(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.0, self.2)
    }

    #[inline]
    pub fn xzyx(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.1, self.0)
    }

    #[inline]
    pub fn xzyy(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.1, self.1)
    }

    #[inline]
    pub fn xzyz(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.1, self.2)
    }

    #[inline]
    pub fn xzzx(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.2, self.0)
    }

    #[inline]
    pub fn xzzy(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.2, self.1)
    }

    #[inline]
    pub fn xzzz(self) -> Vec4 {
        Vec4::new(self.0, self.2, self.2, self.2)
    }

    #[inline]
    pub fn yxxx(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.0, self.0)
    }

    #[inline]
    pub fn yxxy(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.0, self.1)
    }

    #[inline]
    pub fn yxxz(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.0, self.2)
    }

    #[inline]
    pub fn yxyx(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.1, self.0)
    }

    #[inline]
    pub fn yxyy(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.1, self.1)
    }

    #[inline]
    pub fn yxyz(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.1, self.2)
    }

    #[inline]
    pub fn yxzx(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.2, self.0)
    }

    #[inline]
    pub fn yxzy(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.2, self.1)
    }

    #[inline]
    pub fn yxzz(self) -> Vec4 {
        Vec4::new(self.1, self.0, self.2, self.2)
    }

    #[inline]
    pub fn yyxx(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.0, self.0)
    }

    #[inline]
    pub fn yyxy(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.0, self.1)
    }

    #[inline]
    pub fn yyxz(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.0, self.2)
    }

    #[inline]
    pub fn yyyx(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.1, self.0)
    }

    #[inline]
    pub fn yyyy(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.1, self.1)
    }

    #[inline]
    pub fn yyyz(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.1, self.2)
    }

    #[inline]
    pub fn yyzx(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.2, self.0)
    }

    #[inline]
    pub fn yyzy(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.2, self.1)
    }

    #[inline]
    pub fn yyzz(self) -> Vec4 {
        Vec4::new(self.1, self.1, self.2, self.2)
    }

    #[inline]
    pub fn yzxx(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.0, self.0)
    }

    #[inline]
    pub fn yzxy(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.0, self.1)
    }

    #[inline]
    pub fn yzxz(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.0, self.2)
    }

    #[inline]
    pub fn yzyx(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.1, self.0)
    }

    #[inline]
    pub fn yzyy(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.1, self.1)
    }

    #[inline]
    pub fn yzyz(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.1, self.2)
    }

    #[inline]
    pub fn yzzx(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.2, self.0)
    }

    #[inline]
    pub fn yzzy(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.2, self.1)
    }

    #[inline]
    pub fn yzzz(self) -> Vec4 {
        Vec4::new(self.1, self.2, self.2, self.2)
    }

    #[inline]
    pub fn zxxx(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.0, self.0)
    }

    #[inline]
    pub fn zxxy(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.0, self.1)
    }

    #[inline]
    pub fn zxxz(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.0, self.2)
    }

    #[inline]
    pub fn zxyx(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.1, self.0)
    }

    #[inline]
    pub fn zxyy(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.1, self.1)
    }

    #[inline]
    pub fn zxyz(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.1, self.2)
    }

    #[inline]
    pub fn zxzx(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.2, self.0)
    }

    #[inline]
    pub fn zxzy(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.2, self.1)
    }

    #[inline]
    pub fn zxzz(self) -> Vec4 {
        Vec4::new(self.2, self.0, self.2, self.2)
    }

    #[inline]
    pub fn zyxx(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.0, self.0)
    }

    #[inline]
    pub fn zyxy(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.0, self.1)
    }

    #[inline]
    pub fn zyxz(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.0, self.2)
    }

    #[inline]
    pub fn zyyx(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.1, self.0)
    }

    #[inline]
    pub fn zyyy(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.1, self.1)
    }

    #[inline]
    pub fn zyyz(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.1, self.2)
    }

    #[inline]
    pub fn zyzx(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.2, self.0)
    }

    #[inline]
    pub fn zyzy(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.2, self.1)
    }

    #[inline]
    pub fn zyzz(self) -> Vec4 {
        Vec4::new(self.2, self.1, self.2, self.2)
    }

    #[inline]
    pub fn zzxx(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.0, self.0)
    }

    #[inline]
    pub fn zzxy(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.0, self.1)
    }

    #[inline]
    pub fn zzxz(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.0, self.2)
    }

    #[inline]
    pub fn zzyx(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.1, self.0)
    }

    #[inline]
    pub fn zzyy(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.1, self.1)
    }

    #[inline]
    pub fn zzyz(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.1, self.2)
    }

    #[inline]
    pub fn zzzx(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.2, self.0)
    }

    #[inline]
    pub fn zzzy(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.2, self.1)
    }

    #[inline]
    pub fn zzzz(self) -> Vec4 {
        Vec4::new(self.2, self.2, self.2, self.2)
    }

    #[inline]
    pub fn xxx(self) -> Vec3 {
        Vec3(self.0, self.0, self.0)
    }

    #[inline]
    pub fn xxy(self) -> Vec3 {
        Vec3(self.0, self.0, self.1)
    }

    #[inline]
    pub fn xxz(self) -> Vec3 {
        Vec3(self.0, self.0, self.2)
    }

    #[inline]
    pub fn xyx(self) -> Vec3 {
        Vec3(self.0, self.1, self.0)
    }

    #[inline]
    pub fn xyy(self) -> Vec3 {
        Vec3(self.0, self.1, self.1)
    }

    #[inline]
    pub fn xzx(self) -> Vec3 {
        Vec3(self.0, self.2, self.0)
    }

    #[inline]
    pub fn xzy(self) -> Vec3 {
        Vec3(self.0, self.2, self.1)
    }

    #[inline]
    pub fn xzz(self) -> Vec3 {
        Vec3(self.0, self.2, self.2)
    }

    #[inline]
    pub fn yxx(self) -> Vec3 {
        Vec3(self.1, self.0, self.0)
    }

    #[inline]
    pub fn yxy(self) -> Vec3 {
        Vec3(self.1, self.0, self.1)
    }

    #[inline]
    pub fn yxz(self) -> Vec3 {
        Vec3(self.1, self.0, self.2)
    }

    #[inline]
    pub fn yyx(self) -> Vec3 {
        Vec3(self.1, self.1, self.0)
    }

    #[inline]
    pub fn yyy(self) -> Vec3 {
        Vec3(self.1, self.1, self.1)
    }

    #[inline]
    pub fn yyz(self) -> Vec3 {
        Vec3(self.1, self.1, self.2)
    }

    #[inline]
    pub fn yzx(self) -> Vec3 {
        Vec3(self.1, self.2, self.0)
    }

    #[inline]
    pub fn yzy(self) -> Vec3 {
        Vec3(self.1, self.2, self.1)
    }

    #[inline]
    pub fn yzz(self) -> Vec3 {
        Vec3(self.1, self.2, self.2)
    }

    #[inline]
    pub fn zxx(self) -> Vec3 {
        Vec3(self.2, self.0, self.0)
    }

    #[inline]
    pub fn zxy(self) -> Vec3 {
        Vec3(self.2, self.0, self.1)
    }

    #[inline]
    pub fn zxz(self) -> Vec3 {
        Vec3(self.2, self.0, self.2)
    }

    #[inline]
    pub fn zyx(self) -> Vec3 {
        Vec3(self.2, self.1, self.0)
    }

    #[inline]
    pub fn zyy(self) -> Vec3 {
        Vec3(self.2, self.1, self.1)
    }

    #[inline]
    pub fn zyz(self) -> Vec3 {
        Vec3(self.2, self.1, self.2)
    }

    #[inline]
    pub fn zzx(self) -> Vec3 {
        Vec3(self.2, self.2, self.0)
    }

    #[inline]
    pub fn zzy(self) -> Vec3 {
        Vec3(self.2, self.2, self.1)
    }

    #[inline]
    pub fn zzz(self) -> Vec3 {
        Vec3(self.2, self.2, self.2)
    }

    #[inline]
    pub fn xx(self) -> Vec2 {
        Vec2(self.0, self.0)
    }

    #[inline]
    pub fn xy(self) -> Vec2 {
        Vec2(self.0, self.1)
    }

    #[inline]
    pub fn xz(self) -> Vec2 {
        Vec2(self.0, self.2)
    }

    #[inline]
    pub fn yx(self) -> Vec2 {
        Vec2(self.1, self.0)
    }

    #[inline]
    pub fn yy(self) -> Vec2 {
        Vec2(self.1, self.1)
    }

    #[inline]
    pub fn yz(self) -> Vec2 {
        Vec2(self.1, self.2)
    }

    #[inline]
    pub fn zx(self) -> Vec2 {
        Vec2(self.2, self.0)
    }

    #[inline]
    pub fn zy(self) -> Vec2 {
        Vec2(self.2, self.1)
    }

    #[inline]
    pub fn zz(self) -> Vec2 {
        Vec2(self.2, self.2)
    }

}
