// Generated by swizzlegen. Do not edit.

use super::{Vec2, Vec3, Vec4};

#[cfg(all(vec4_sse2, target_arch = "x86"))]
use core::arch::x86::*;
#[cfg(all(vec4_sse2, target_arch = "x86_64"))]
use core::arch::x86_64::*;

pub trait Vec4Swizzles {
    fn xxxx(self) -> Vec4;
    fn xxxy(self) -> Vec4;
    fn xxxz(self) -> Vec4;
    fn xxxw(self) -> Vec4;
    fn xxyx(self) -> Vec4;
    fn xxyy(self) -> Vec4;
    fn xxyz(self) -> Vec4;
    fn xxyw(self) -> Vec4;
    fn xxzx(self) -> Vec4;
    fn xxzy(self) -> Vec4;
    fn xxzz(self) -> Vec4;
    fn xxzw(self) -> Vec4;
    fn xxwx(self) -> Vec4;
    fn xxwy(self) -> Vec4;
    fn xxwz(self) -> Vec4;
    fn xxww(self) -> Vec4;
    fn xyxx(self) -> Vec4;
    fn xyxy(self) -> Vec4;
    fn xyxz(self) -> Vec4;
    fn xyxw(self) -> Vec4;
    fn xyyx(self) -> Vec4;
    fn xyyy(self) -> Vec4;
    fn xyyz(self) -> Vec4;
    fn xyyw(self) -> Vec4;
    fn xyzx(self) -> Vec4;
    fn xyzy(self) -> Vec4;
    fn xyzz(self) -> Vec4;
    fn xywx(self) -> Vec4;
    fn xywy(self) -> Vec4;
    fn xywz(self) -> Vec4;
    fn xyww(self) -> Vec4;
    fn xzxx(self) -> Vec4;
    fn xzxy(self) -> Vec4;
    fn xzxz(self) -> Vec4;
    fn xzxw(self) -> Vec4;
    fn xzyx(self) -> Vec4;
    fn xzyy(self) -> Vec4;
    fn xzyz(self) -> Vec4;
    fn xzyw(self) -> Vec4;
    fn xzzx(self) -> Vec4;
    fn xzzy(self) -> Vec4;
    fn xzzz(self) -> Vec4;
    fn xzzw(self) -> Vec4;
    fn xzwx(self) -> Vec4;
    fn xzwy(self) -> Vec4;
    fn xzwz(self) -> Vec4;
    fn xzww(self) -> Vec4;
    fn xwxx(self) -> Vec4;
    fn xwxy(self) -> Vec4;
    fn xwxz(self) -> Vec4;
    fn xwxw(self) -> Vec4;
    fn xwyx(self) -> Vec4;
    fn xwyy(self) -> Vec4;
    fn xwyz(self) -> Vec4;
    fn xwyw(self) -> Vec4;
    fn xwzx(self) -> Vec4;
    fn xwzy(self) -> Vec4;
    fn xwzz(self) -> Vec4;
    fn xwzw(self) -> Vec4;
    fn xwwx(self) -> Vec4;
    fn xwwy(self) -> Vec4;
    fn xwwz(self) -> Vec4;
    fn xwww(self) -> Vec4;
    fn yxxx(self) -> Vec4;
    fn yxxy(self) -> Vec4;
    fn yxxz(self) -> Vec4;
    fn yxxw(self) -> Vec4;
    fn yxyx(self) -> Vec4;
    fn yxyy(self) -> Vec4;
    fn yxyz(self) -> Vec4;
    fn yxyw(self) -> Vec4;
    fn yxzx(self) -> Vec4;
    fn yxzy(self) -> Vec4;
    fn yxzz(self) -> Vec4;
    fn yxzw(self) -> Vec4;
    fn yxwx(self) -> Vec4;
    fn yxwy(self) -> Vec4;
    fn yxwz(self) -> Vec4;
    fn yxww(self) -> Vec4;
    fn yyxx(self) -> Vec4;
    fn yyxy(self) -> Vec4;
    fn yyxz(self) -> Vec4;
    fn yyxw(self) -> Vec4;
    fn yyyx(self) -> Vec4;
    fn yyyy(self) -> Vec4;
    fn yyyz(self) -> Vec4;
    fn yyyw(self) -> Vec4;
    fn yyzx(self) -> Vec4;
    fn yyzy(self) -> Vec4;
    fn yyzz(self) -> Vec4;
    fn yyzw(self) -> Vec4;
    fn yywx(self) -> Vec4;
    fn yywy(self) -> Vec4;
    fn yywz(self) -> Vec4;
    fn yyww(self) -> Vec4;
    fn yzxx(self) -> Vec4;
    fn yzxy(self) -> Vec4;
    fn yzxz(self) -> Vec4;
    fn yzxw(self) -> Vec4;
    fn yzyx(self) -> Vec4;
    fn yzyy(self) -> Vec4;
    fn yzyz(self) -> Vec4;
    fn yzyw(self) -> Vec4;
    fn yzzx(self) -> Vec4;
    fn yzzy(self) -> Vec4;
    fn yzzz(self) -> Vec4;
    fn yzzw(self) -> Vec4;
    fn yzwx(self) -> Vec4;
    fn yzwy(self) -> Vec4;
    fn yzwz(self) -> Vec4;
    fn yzww(self) -> Vec4;
    fn ywxx(self) -> Vec4;
    fn ywxy(self) -> Vec4;
    fn ywxz(self) -> Vec4;
    fn ywxw(self) -> Vec4;
    fn ywyx(self) -> Vec4;
    fn ywyy(self) -> Vec4;
    fn ywyz(self) -> Vec4;
    fn ywyw(self) -> Vec4;
    fn ywzx(self) -> Vec4;
    fn ywzy(self) -> Vec4;
    fn ywzz(self) -> Vec4;
    fn ywzw(self) -> Vec4;
    fn ywwx(self) -> Vec4;
    fn ywwy(self) -> Vec4;
    fn ywwz(self) -> Vec4;
    fn ywww(self) -> Vec4;
    fn zxxx(self) -> Vec4;
    fn zxxy(self) -> Vec4;
    fn zxxz(self) -> Vec4;
    fn zxxw(self) -> Vec4;
    fn zxyx(self) -> Vec4;
    fn zxyy(self) -> Vec4;
    fn zxyz(self) -> Vec4;
    fn zxyw(self) -> Vec4;
    fn zxzx(self) -> Vec4;
    fn zxzy(self) -> Vec4;
    fn zxzz(self) -> Vec4;
    fn zxzw(self) -> Vec4;
    fn zxwx(self) -> Vec4;
    fn zxwy(self) -> Vec4;
    fn zxwz(self) -> Vec4;
    fn zxww(self) -> Vec4;
    fn zyxx(self) -> Vec4;
    fn zyxy(self) -> Vec4;
    fn zyxz(self) -> Vec4;
    fn zyxw(self) -> Vec4;
    fn zyyx(self) -> Vec4;
    fn zyyy(self) -> Vec4;
    fn zyyz(self) -> Vec4;
    fn zyyw(self) -> Vec4;
    fn zyzx(self) -> Vec4;
    fn zyzy(self) -> Vec4;
    fn zyzz(self) -> Vec4;
    fn zyzw(self) -> Vec4;
    fn zywx(self) -> Vec4;
    fn zywy(self) -> Vec4;
    fn zywz(self) -> Vec4;
    fn zyww(self) -> Vec4;
    fn zzxx(self) -> Vec4;
    fn zzxy(self) -> Vec4;
    fn zzxz(self) -> Vec4;
    fn zzxw(self) -> Vec4;
    fn zzyx(self) -> Vec4;
    fn zzyy(self) -> Vec4;
    fn zzyz(self) -> Vec4;
    fn zzyw(self) -> Vec4;
    fn zzzx(self) -> Vec4;
    fn zzzy(self) -> Vec4;
    fn zzzz(self) -> Vec4;
    fn zzzw(self) -> Vec4;
    fn zzwx(self) -> Vec4;
    fn zzwy(self) -> Vec4;
    fn zzwz(self) -> Vec4;
    fn zzww(self) -> Vec4;
    fn zwxx(self) -> Vec4;
    fn zwxy(self) -> Vec4;
    fn zwxz(self) -> Vec4;
    fn zwxw(self) -> Vec4;
    fn zwyx(self) -> Vec4;
    fn zwyy(self) -> Vec4;
    fn zwyz(self) -> Vec4;
    fn zwyw(self) -> Vec4;
    fn zwzx(self) -> Vec4;
    fn zwzy(self) -> Vec4;
    fn zwzz(self) -> Vec4;
    fn zwzw(self) -> Vec4;
    fn zwwx(self) -> Vec4;
    fn zwwy(self) -> Vec4;
    fn zwwz(self) -> Vec4;
    fn zwww(self) -> Vec4;
    fn wxxx(self) -> Vec4;
    fn wxxy(self) -> Vec4;
    fn wxxz(self) -> Vec4;
    fn wxxw(self) -> Vec4;
    fn wxyx(self) -> Vec4;
    fn wxyy(self) -> Vec4;
    fn wxyz(self) -> Vec4;
    fn wxyw(self) -> Vec4;
    fn wxzx(self) -> Vec4;
    fn wxzy(self) -> Vec4;
    fn wxzz(self) -> Vec4;
    fn wxzw(self) -> Vec4;
    fn wxwx(self) -> Vec4;
    fn wxwy(self) -> Vec4;
    fn wxwz(self) -> Vec4;
    fn wxww(self) -> Vec4;
    fn wyxx(self) -> Vec4;
    fn wyxy(self) -> Vec4;
    fn wyxz(self) -> Vec4;
    fn wyxw(self) -> Vec4;
    fn wyyx(self) -> Vec4;
    fn wyyy(self) -> Vec4;
    fn wyyz(self) -> Vec4;
    fn wyyw(self) -> Vec4;
    fn wyzx(self) -> Vec4;
    fn wyzy(self) -> Vec4;
    fn wyzz(self) -> Vec4;
    fn wyzw(self) -> Vec4;
    fn wywx(self) -> Vec4;
    fn wywy(self) -> Vec4;
    fn wywz(self) -> Vec4;
    fn wyww(self) -> Vec4;
    fn wzxx(self) -> Vec4;
    fn wzxy(self) -> Vec4;
    fn wzxz(self) -> Vec4;
    fn wzxw(self) -> Vec4;
    fn wzyx(self) -> Vec4;
    fn wzyy(self) -> Vec4;
    fn wzyz(self) -> Vec4;
    fn wzyw(self) -> Vec4;
    fn wzzx(self) -> Vec4;
    fn wzzy(self) -> Vec4;
    fn wzzz(self) -> Vec4;
    fn wzzw(self) -> Vec4;
    fn wzwx(self) -> Vec4;
    fn wzwy(self) -> Vec4;
    fn wzwz(self) -> Vec4;
    fn wzww(self) -> Vec4;
    fn wwxx(self) -> Vec4;
    fn wwxy(self) -> Vec4;
    fn wwxz(self) -> Vec4;
    fn wwxw(self) -> Vec4;
    fn wwyx(self) -> Vec4;
    fn wwyy(self) -> Vec4;
    fn wwyz(self) -> Vec4;
    fn wwyw(self) -> Vec4;
    fn wwzx(self) -> Vec4;
    fn wwzy(self) -> Vec4;
    fn wwzz(self) -> Vec4;
    fn wwzw(self) -> Vec4;
    fn wwwx(self) -> Vec4;
    fn wwwy(self) -> Vec4;
    fn wwwz(self) -> Vec4;
    fn wwww(self) -> Vec4;
    fn xxx(self) -> Vec3;
    fn xxy(self) -> Vec3;
    fn xxz(self) -> Vec3;
    fn xxw(self) -> Vec3;
    fn xyx(self) -> Vec3;
    fn xyy(self) -> Vec3;
    fn xyz(self) -> Vec3;
    fn xyw(self) -> Vec3;
    fn xzx(self) -> Vec3;
    fn xzy(self) -> Vec3;
    fn xzz(self) -> Vec3;
    fn xzw(self) -> Vec3;
    fn xwx(self) -> Vec3;
    fn xwy(self) -> Vec3;
    fn xwz(self) -> Vec3;
    fn xww(self) -> Vec3;
    fn yxx(self) -> Vec3;
    fn yxy(self) -> Vec3;
    fn yxz(self) -> Vec3;
    fn yxw(self) -> Vec3;
    fn yyx(self) -> Vec3;
    fn yyy(self) -> Vec3;
    fn yyz(self) -> Vec3;
    fn yyw(self) -> Vec3;
    fn yzx(self) -> Vec3;
    fn yzy(self) -> Vec3;
    fn yzz(self) -> Vec3;
    fn yzw(self) -> Vec3;
    fn ywx(self) -> Vec3;
    fn ywy(self) -> Vec3;
    fn ywz(self) -> Vec3;
    fn yww(self) -> Vec3;
    fn zxx(self) -> Vec3;
    fn zxy(self) -> Vec3;
    fn zxz(self) -> Vec3;
    fn zxw(self) -> Vec3;
    fn zyx(self) -> Vec3;
    fn zyy(self) -> Vec3;
    fn zyz(self) -> Vec3;
    fn zyw(self) -> Vec3;
    fn zzx(self) -> Vec3;
    fn zzy(self) -> Vec3;
    fn zzz(self) -> Vec3;
    fn zzw(self) -> Vec3;
    fn zwx(self) -> Vec3;
    fn zwy(self) -> Vec3;
    fn zwz(self) -> Vec3;
    fn zww(self) -> Vec3;
    fn wxx(self) -> Vec3;
    fn wxy(self) -> Vec3;
    fn wxz(self) -> Vec3;
    fn wxw(self) -> Vec3;
    fn wyx(self) -> Vec3;
    fn wyy(self) -> Vec3;
    fn wyz(self) -> Vec3;
    fn wyw(self) -> Vec3;
    fn wzx(self) -> Vec3;
    fn wzy(self) -> Vec3;
    fn wzz(self) -> Vec3;
    fn wzw(self) -> Vec3;
    fn wwx(self) -> Vec3;
    fn wwy(self) -> Vec3;
    fn wwz(self) -> Vec3;
    fn www(self) -> Vec3;
    fn xx(self) -> Vec2;
    fn xy(self) -> Vec2;
    fn xz(self) -> Vec2;
    fn xw(self) -> Vec2;
    fn yx(self) -> Vec2;
    fn yy(self) -> Vec2;
    fn yz(self) -> Vec2;
    fn yw(self) -> Vec2;
    fn zx(self) -> Vec2;
    fn zy(self) -> Vec2;
    fn zz(self) -> Vec2;
    fn zw(self) -> Vec2;
    fn wx(self) -> Vec2;
    fn wy(self) -> Vec2;
    fn wz(self) -> Vec2;
    fn ww(self) -> Vec2;
}

impl Vec4Swizzles for Vec4 {
    #[inline]
    fn xxxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.0, self.0)
        }
    }
    #[inline]
    fn xxxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.0, self.1)
        }
    }
    #[inline]
    fn xxxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.0, self.2)
        }
    }
    #[inline]
    fn xxxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.0, self.3)
        }
    }
    #[inline]
    fn xxyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.1, self.0)
        }
    }
    #[inline]
    fn xxyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.1, self.1)
        }
    }
    #[inline]
    fn xxyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.1, self.2)
        }
    }
    #[inline]
    fn xxyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.1, self.3)
        }
    }
    #[inline]
    fn xxzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.2, self.0)
        }
    }
    #[inline]
    fn xxzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.2, self.1)
        }
    }
    #[inline]
    fn xxzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.2, self.2)
        }
    }
    #[inline]
    fn xxzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.2, self.3)
        }
    }
    #[inline]
    fn xxwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.3, self.0)
        }
    }
    #[inline]
    fn xxwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.3, self.1)
        }
    }
    #[inline]
    fn xxwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.3, self.2)
        }
    }
    #[inline]
    fn xxww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_00_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.0, self.3, self.3)
        }
    }
    #[inline]
    fn xyxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.0, self.0)
        }
    }
    #[inline]
    fn xyxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.0, self.1)
        }
    }
    #[inline]
    fn xyxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.0, self.2)
        }
    }
    #[inline]
    fn xyxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.0, self.3)
        }
    }
    #[inline]
    fn xyyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.1, self.0)
        }
    }
    #[inline]
    fn xyyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.1, self.1)
        }
    }
    #[inline]
    fn xyyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.1, self.2)
        }
    }
    #[inline]
    fn xyyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.1, self.3)
        }
    }
    #[inline]
    fn xyzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.2, self.0)
        }
    }
    #[inline]
    fn xyzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.2, self.1)
        }
    }
    #[inline]
    fn xyzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.2, self.2)
        }
    }
    #[inline]
    fn xywx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.3, self.0)
        }
    }
    #[inline]
    fn xywy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.3, self.1)
        }
    }
    #[inline]
    fn xywz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.3, self.2)
        }
    }
    #[inline]
    fn xyww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_01_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.1, self.3, self.3)
        }
    }
    #[inline]
    fn xzxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.0, self.0)
        }
    }
    #[inline]
    fn xzxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.0, self.1)
        }
    }
    #[inline]
    fn xzxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.0, self.2)
        }
    }
    #[inline]
    fn xzxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.0, self.3)
        }
    }
    #[inline]
    fn xzyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.1, self.0)
        }
    }
    #[inline]
    fn xzyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.1, self.1)
        }
    }
    #[inline]
    fn xzyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.1, self.2)
        }
    }
    #[inline]
    fn xzyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.1, self.3)
        }
    }
    #[inline]
    fn xzzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.2, self.0)
        }
    }
    #[inline]
    fn xzzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.2, self.1)
        }
    }
    #[inline]
    fn xzzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.2, self.2)
        }
    }
    #[inline]
    fn xzzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.2, self.3)
        }
    }
    #[inline]
    fn xzwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.3, self.0)
        }
    }
    #[inline]
    fn xzwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.3, self.1)
        }
    }
    #[inline]
    fn xzwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.3, self.2)
        }
    }
    #[inline]
    fn xzww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_10_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.2, self.3, self.3)
        }
    }
    #[inline]
    fn xwxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.0, self.0)
        }
    }
    #[inline]
    fn xwxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.0, self.1)
        }
    }
    #[inline]
    fn xwxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.0, self.2)
        }
    }
    #[inline]
    fn xwxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.0, self.3)
        }
    }
    #[inline]
    fn xwyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.1, self.0)
        }
    }
    #[inline]
    fn xwyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.1, self.1)
        }
    }
    #[inline]
    fn xwyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.1, self.2)
        }
    }
    #[inline]
    fn xwyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.1, self.3)
        }
    }
    #[inline]
    fn xwzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.2, self.0)
        }
    }
    #[inline]
    fn xwzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.2, self.1)
        }
    }
    #[inline]
    fn xwzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.2, self.2)
        }
    }
    #[inline]
    fn xwzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.2, self.3)
        }
    }
    #[inline]
    fn xwwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.3, self.0)
        }
    }
    #[inline]
    fn xwwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.3, self.1)
        }
    }
    #[inline]
    fn xwwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.3, self.2)
        }
    }
    #[inline]
    fn xwww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_11_00))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.0, self.3, self.3, self.3)
        }
    }
    #[inline]
    fn yxxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.0, self.0)
        }
    }
    #[inline]
    fn yxxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.0, self.1)
        }
    }
    #[inline]
    fn yxxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.0, self.2)
        }
    }
    #[inline]
    fn yxxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.0, self.3)
        }
    }
    #[inline]
    fn yxyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.1, self.0)
        }
    }
    #[inline]
    fn yxyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.1, self.1)
        }
    }
    #[inline]
    fn yxyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.1, self.2)
        }
    }
    #[inline]
    fn yxyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.1, self.3)
        }
    }
    #[inline]
    fn yxzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.2, self.0)
        }
    }
    #[inline]
    fn yxzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.2, self.1)
        }
    }
    #[inline]
    fn yxzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.2, self.2)
        }
    }
    #[inline]
    fn yxzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.2, self.3)
        }
    }
    #[inline]
    fn yxwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.3, self.0)
        }
    }
    #[inline]
    fn yxwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.3, self.1)
        }
    }
    #[inline]
    fn yxwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.3, self.2)
        }
    }
    #[inline]
    fn yxww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_00_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.0, self.3, self.3)
        }
    }
    #[inline]
    fn yyxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.0, self.0)
        }
    }
    #[inline]
    fn yyxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.0, self.1)
        }
    }
    #[inline]
    fn yyxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.0, self.2)
        }
    }
    #[inline]
    fn yyxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.0, self.3)
        }
    }
    #[inline]
    fn yyyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.1, self.0)
        }
    }
    #[inline]
    fn yyyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.1, self.1)
        }
    }
    #[inline]
    fn yyyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.1, self.2)
        }
    }
    #[inline]
    fn yyyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.1, self.3)
        }
    }
    #[inline]
    fn yyzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.2, self.0)
        }
    }
    #[inline]
    fn yyzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.2, self.1)
        }
    }
    #[inline]
    fn yyzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.2, self.2)
        }
    }
    #[inline]
    fn yyzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.2, self.3)
        }
    }
    #[inline]
    fn yywx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.3, self.0)
        }
    }
    #[inline]
    fn yywy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.3, self.1)
        }
    }
    #[inline]
    fn yywz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.3, self.2)
        }
    }
    #[inline]
    fn yyww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_01_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.1, self.3, self.3)
        }
    }
    #[inline]
    fn yzxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.0, self.0)
        }
    }
    #[inline]
    fn yzxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.0, self.1)
        }
    }
    #[inline]
    fn yzxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.0, self.2)
        }
    }
    #[inline]
    fn yzxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.0, self.3)
        }
    }
    #[inline]
    fn yzyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.1, self.0)
        }
    }
    #[inline]
    fn yzyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.1, self.1)
        }
    }
    #[inline]
    fn yzyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.1, self.2)
        }
    }
    #[inline]
    fn yzyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.1, self.3)
        }
    }
    #[inline]
    fn yzzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.2, self.0)
        }
    }
    #[inline]
    fn yzzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.2, self.1)
        }
    }
    #[inline]
    fn yzzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.2, self.2)
        }
    }
    #[inline]
    fn yzzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.2, self.3)
        }
    }
    #[inline]
    fn yzwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.3, self.0)
        }
    }
    #[inline]
    fn yzwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.3, self.1)
        }
    }
    #[inline]
    fn yzwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.3, self.2)
        }
    }
    #[inline]
    fn yzww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_10_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.2, self.3, self.3)
        }
    }
    #[inline]
    fn ywxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.0, self.0)
        }
    }
    #[inline]
    fn ywxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.0, self.1)
        }
    }
    #[inline]
    fn ywxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.0, self.2)
        }
    }
    #[inline]
    fn ywxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.0, self.3)
        }
    }
    #[inline]
    fn ywyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.1, self.0)
        }
    }
    #[inline]
    fn ywyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.1, self.1)
        }
    }
    #[inline]
    fn ywyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.1, self.2)
        }
    }
    #[inline]
    fn ywyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.1, self.3)
        }
    }
    #[inline]
    fn ywzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.2, self.0)
        }
    }
    #[inline]
    fn ywzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.2, self.1)
        }
    }
    #[inline]
    fn ywzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.2, self.2)
        }
    }
    #[inline]
    fn ywzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.2, self.3)
        }
    }
    #[inline]
    fn ywwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.3, self.0)
        }
    }
    #[inline]
    fn ywwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.3, self.1)
        }
    }
    #[inline]
    fn ywwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.3, self.2)
        }
    }
    #[inline]
    fn ywww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_11_01))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.1, self.3, self.3, self.3)
        }
    }
    #[inline]
    fn zxxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.0, self.0)
        }
    }
    #[inline]
    fn zxxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.0, self.1)
        }
    }
    #[inline]
    fn zxxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.0, self.2)
        }
    }
    #[inline]
    fn zxxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.0, self.3)
        }
    }
    #[inline]
    fn zxyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.1, self.0)
        }
    }
    #[inline]
    fn zxyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.1, self.1)
        }
    }
    #[inline]
    fn zxyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.1, self.2)
        }
    }
    #[inline]
    fn zxyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.1, self.3)
        }
    }
    #[inline]
    fn zxzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.2, self.0)
        }
    }
    #[inline]
    fn zxzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.2, self.1)
        }
    }
    #[inline]
    fn zxzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.2, self.2)
        }
    }
    #[inline]
    fn zxzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.2, self.3)
        }
    }
    #[inline]
    fn zxwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.3, self.0)
        }
    }
    #[inline]
    fn zxwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.3, self.1)
        }
    }
    #[inline]
    fn zxwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.3, self.2)
        }
    }
    #[inline]
    fn zxww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_00_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.0, self.3, self.3)
        }
    }
    #[inline]
    fn zyxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.0, self.0)
        }
    }
    #[inline]
    fn zyxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.0, self.1)
        }
    }
    #[inline]
    fn zyxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.0, self.2)
        }
    }
    #[inline]
    fn zyxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.0, self.3)
        }
    }
    #[inline]
    fn zyyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.1, self.0)
        }
    }
    #[inline]
    fn zyyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.1, self.1)
        }
    }
    #[inline]
    fn zyyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.1, self.2)
        }
    }
    #[inline]
    fn zyyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.1, self.3)
        }
    }
    #[inline]
    fn zyzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.2, self.0)
        }
    }
    #[inline]
    fn zyzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.2, self.1)
        }
    }
    #[inline]
    fn zyzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.2, self.2)
        }
    }
    #[inline]
    fn zyzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.2, self.3)
        }
    }
    #[inline]
    fn zywx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.3, self.0)
        }
    }
    #[inline]
    fn zywy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.3, self.1)
        }
    }
    #[inline]
    fn zywz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.3, self.2)
        }
    }
    #[inline]
    fn zyww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_01_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.1, self.3, self.3)
        }
    }
    #[inline]
    fn zzxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.0, self.0)
        }
    }
    #[inline]
    fn zzxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.0, self.1)
        }
    }
    #[inline]
    fn zzxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.0, self.2)
        }
    }
    #[inline]
    fn zzxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.0, self.3)
        }
    }
    #[inline]
    fn zzyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.1, self.0)
        }
    }
    #[inline]
    fn zzyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.1, self.1)
        }
    }
    #[inline]
    fn zzyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.1, self.2)
        }
    }
    #[inline]
    fn zzyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.1, self.3)
        }
    }
    #[inline]
    fn zzzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.2, self.0)
        }
    }
    #[inline]
    fn zzzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.2, self.1)
        }
    }
    #[inline]
    fn zzzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.2, self.2)
        }
    }
    #[inline]
    fn zzzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.2, self.3)
        }
    }
    #[inline]
    fn zzwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.3, self.0)
        }
    }
    #[inline]
    fn zzwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.3, self.1)
        }
    }
    #[inline]
    fn zzwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.3, self.2)
        }
    }
    #[inline]
    fn zzww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_10_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.2, self.3, self.3)
        }
    }
    #[inline]
    fn zwxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.0, self.0)
        }
    }
    #[inline]
    fn zwxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.0, self.1)
        }
    }
    #[inline]
    fn zwxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.0, self.2)
        }
    }
    #[inline]
    fn zwxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.0, self.3)
        }
    }
    #[inline]
    fn zwyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.1, self.0)
        }
    }
    #[inline]
    fn zwyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.1, self.1)
        }
    }
    #[inline]
    fn zwyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.1, self.2)
        }
    }
    #[inline]
    fn zwyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.1, self.3)
        }
    }
    #[inline]
    fn zwzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.2, self.0)
        }
    }
    #[inline]
    fn zwzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.2, self.1)
        }
    }
    #[inline]
    fn zwzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.2, self.2)
        }
    }
    #[inline]
    fn zwzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.2, self.3)
        }
    }
    #[inline]
    fn zwwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.3, self.0)
        }
    }
    #[inline]
    fn zwwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.3, self.1)
        }
    }
    #[inline]
    fn zwwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.3, self.2)
        }
    }
    #[inline]
    fn zwww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_11_10))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.2, self.3, self.3, self.3)
        }
    }
    #[inline]
    fn wxxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.0, self.0)
        }
    }
    #[inline]
    fn wxxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.0, self.1)
        }
    }
    #[inline]
    fn wxxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.0, self.2)
        }
    }
    #[inline]
    fn wxxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.0, self.3)
        }
    }
    #[inline]
    fn wxyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.1, self.0)
        }
    }
    #[inline]
    fn wxyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.1, self.1)
        }
    }
    #[inline]
    fn wxyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.1, self.2)
        }
    }
    #[inline]
    fn wxyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.1, self.3)
        }
    }
    #[inline]
    fn wxzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.2, self.0)
        }
    }
    #[inline]
    fn wxzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.2, self.1)
        }
    }
    #[inline]
    fn wxzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.2, self.2)
        }
    }
    #[inline]
    fn wxzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.2, self.3)
        }
    }
    #[inline]
    fn wxwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.3, self.0)
        }
    }
    #[inline]
    fn wxwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.3, self.1)
        }
    }
    #[inline]
    fn wxwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.3, self.2)
        }
    }
    #[inline]
    fn wxww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_00_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.0, self.3, self.3)
        }
    }
    #[inline]
    fn wyxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.0, self.0)
        }
    }
    #[inline]
    fn wyxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.0, self.1)
        }
    }
    #[inline]
    fn wyxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.0, self.2)
        }
    }
    #[inline]
    fn wyxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.0, self.3)
        }
    }
    #[inline]
    fn wyyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.1, self.0)
        }
    }
    #[inline]
    fn wyyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.1, self.1)
        }
    }
    #[inline]
    fn wyyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.1, self.2)
        }
    }
    #[inline]
    fn wyyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.1, self.3)
        }
    }
    #[inline]
    fn wyzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.2, self.0)
        }
    }
    #[inline]
    fn wyzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.2, self.1)
        }
    }
    #[inline]
    fn wyzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.2, self.2)
        }
    }
    #[inline]
    fn wyzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.2, self.3)
        }
    }
    #[inline]
    fn wywx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.3, self.0)
        }
    }
    #[inline]
    fn wywy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.3, self.1)
        }
    }
    #[inline]
    fn wywz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.3, self.2)
        }
    }
    #[inline]
    fn wyww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_01_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.1, self.3, self.3)
        }
    }
    #[inline]
    fn wzxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.0, self.0)
        }
    }
    #[inline]
    fn wzxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.0, self.1)
        }
    }
    #[inline]
    fn wzxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.0, self.2)
        }
    }
    #[inline]
    fn wzxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.0, self.3)
        }
    }
    #[inline]
    fn wzyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.1, self.0)
        }
    }
    #[inline]
    fn wzyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.1, self.1)
        }
    }
    #[inline]
    fn wzyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.1, self.2)
        }
    }
    #[inline]
    fn wzyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.1, self.3)
        }
    }
    #[inline]
    fn wzzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.2, self.0)
        }
    }
    #[inline]
    fn wzzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.2, self.1)
        }
    }
    #[inline]
    fn wzzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.2, self.2)
        }
    }
    #[inline]
    fn wzzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.2, self.3)
        }
    }
    #[inline]
    fn wzwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.3, self.0)
        }
    }
    #[inline]
    fn wzwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.3, self.1)
        }
    }
    #[inline]
    fn wzwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.3, self.2)
        }
    }
    #[inline]
    fn wzww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_10_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.2, self.3, self.3)
        }
    }
    #[inline]
    fn wwxx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.0, self.0)
        }
    }
    #[inline]
    fn wwxy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_00_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.0, self.1)
        }
    }
    #[inline]
    fn wwxz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_00_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.0, self.2)
        }
    }
    #[inline]
    fn wwxw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_00_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.0, self.3)
        }
    }
    #[inline]
    fn wwyx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.1, self.0)
        }
    }
    #[inline]
    fn wwyy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_01_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.1, self.1)
        }
    }
    #[inline]
    fn wwyz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_01_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.1, self.2)
        }
    }
    #[inline]
    fn wwyw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_01_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.1, self.3)
        }
    }
    #[inline]
    fn wwzx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.2, self.0)
        }
    }
    #[inline]
    fn wwzy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_10_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.2, self.1)
        }
    }
    #[inline]
    fn wwzz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_10_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.2, self.2)
        }
    }
    #[inline]
    fn wwzw(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_10_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.2, self.3)
        }
    }
    #[inline]
    fn wwwx(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.3, self.0)
        }
    }
    #[inline]
    fn wwwy(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b01_11_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.3, self.1)
        }
    }
    #[inline]
    fn wwwz(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b10_11_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.3, self.2)
        }
    }
    #[inline]
    fn wwww(self) -> Vec4 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec4(_mm_shuffle_ps(self.0, self.0, 0b11_11_11_11))
        }

        #[cfg(vec4_f32)]
        {
            Vec4(self.3, self.3, self.3, self.3)
        }
    }
    #[inline]
    fn xxx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.0, self.0)
        }
    }
    #[inline]
    fn xxy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.0, self.1)
        }
    }
    #[inline]
    fn xxz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.0, self.2)
        }
    }
    #[inline]
    fn xxw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.0, self.3)
        }
    }
    #[inline]
    fn xyx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.1, self.0)
        }
    }
    #[inline]
    fn xyy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.1, self.1)
        }
    }
    #[inline]
    fn xyz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.1, self.2)
        }
    }
    #[inline]
    fn xyw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.1, self.3)
        }
    }
    #[inline]
    fn xzx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.2, self.0)
        }
    }
    #[inline]
    fn xzy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.2, self.1)
        }
    }
    #[inline]
    fn xzz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.2, self.2)
        }
    }
    #[inline]
    fn xzw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.2, self.3)
        }
    }
    #[inline]
    fn xwx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.3, self.0)
        }
    }
    #[inline]
    fn xwy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.3, self.1)
        }
    }
    #[inline]
    fn xwz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.3, self.2)
        }
    }
    #[inline]
    fn xww(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.0, self.3, self.3)
        }
    }
    #[inline]
    fn yxx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.0, self.0)
        }
    }
    #[inline]
    fn yxy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.0, self.1)
        }
    }
    #[inline]
    fn yxz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.0, self.2)
        }
    }
    #[inline]
    fn yxw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.0, self.3)
        }
    }
    #[inline]
    fn yyx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.1, self.0)
        }
    }
    #[inline]
    fn yyy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.1, self.1)
        }
    }
    #[inline]
    fn yyz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.1, self.2)
        }
    }
    #[inline]
    fn yyw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.1, self.3)
        }
    }
    #[inline]
    fn yzx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.2, self.0)
        }
    }
    #[inline]
    fn yzy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.2, self.1)
        }
    }
    #[inline]
    fn yzz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.2, self.2)
        }
    }
    #[inline]
    fn yzw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.2, self.3)
        }
    }
    #[inline]
    fn ywx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.3, self.0)
        }
    }
    #[inline]
    fn ywy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.3, self.1)
        }
    }
    #[inline]
    fn ywz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.3, self.2)
        }
    }
    #[inline]
    fn yww(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.1, self.3, self.3)
        }
    }
    #[inline]
    fn zxx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.0, self.0)
        }
    }
    #[inline]
    fn zxy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.0, self.1)
        }
    }
    #[inline]
    fn zxz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.0, self.2)
        }
    }
    #[inline]
    fn zxw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.0, self.3)
        }
    }
    #[inline]
    fn zyx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.1, self.0)
        }
    }
    #[inline]
    fn zyy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.1, self.1)
        }
    }
    #[inline]
    fn zyz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.1, self.2)
        }
    }
    #[inline]
    fn zyw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.1, self.3)
        }
    }
    #[inline]
    fn zzx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.2, self.0)
        }
    }
    #[inline]
    fn zzy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.2, self.1)
        }
    }
    #[inline]
    fn zzz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.2, self.2)
        }
    }
    #[inline]
    fn zzw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.2, self.3)
        }
    }
    #[inline]
    fn zwx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.3, self.0)
        }
    }
    #[inline]
    fn zwy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.3, self.1)
        }
    }
    #[inline]
    fn zwz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.3, self.2)
        }
    }
    #[inline]
    fn zww(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.2, self.3, self.3)
        }
    }
    #[inline]
    fn wxx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.0, self.0)
        }
    }
    #[inline]
    fn wxy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_00_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.0, self.1)
        }
    }
    #[inline]
    fn wxz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_00_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.0, self.2)
        }
    }
    #[inline]
    fn wxw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_00_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.0, self.3)
        }
    }
    #[inline]
    fn wyx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.1, self.0)
        }
    }
    #[inline]
    fn wyy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_01_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.1, self.1)
        }
    }
    #[inline]
    fn wyz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_01_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.1, self.2)
        }
    }
    #[inline]
    fn wyw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_01_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.1, self.3)
        }
    }
    #[inline]
    fn wzx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.2, self.0)
        }
    }
    #[inline]
    fn wzy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_10_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.2, self.1)
        }
    }
    #[inline]
    fn wzz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_10_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.2, self.2)
        }
    }
    #[inline]
    fn wzw(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_10_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.2, self.3)
        }
    }
    #[inline]
    fn wwx(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.3, self.0)
        }
    }
    #[inline]
    fn wwy(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_01_11_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.3, self.1)
        }
    }
    #[inline]
    fn wwz(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_10_11_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.3, self.2)
        }
    }
    #[inline]
    fn www(self) -> Vec3 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec3::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_11_11_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec3(self.3, self.3, self.3)
        }
    }
    #[inline]
    fn xx(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.0, self.0)
        }
    }
    #[inline]
    fn xy(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.0, self.1)
        }
    }
    #[inline]
    fn xz(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.0, self.2)
        }
    }
    #[inline]
    fn xw(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_00)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.0, self.3)
        }
    }
    #[inline]
    fn yx(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.1, self.0)
        }
    }
    #[inline]
    fn yy(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.1, self.1)
        }
    }
    #[inline]
    fn yz(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.1, self.2)
        }
    }
    #[inline]
    fn yw(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_01)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.1, self.3)
        }
    }
    #[inline]
    fn zx(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.2, self.0)
        }
    }
    #[inline]
    fn zy(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.2, self.1)
        }
    }
    #[inline]
    fn zz(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.2, self.2)
        }
    }
    #[inline]
    fn zw(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_10)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.2, self.3)
        }
    }
    #[inline]
    fn wx(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_00_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.3, self.0)
        }
    }
    #[inline]
    fn wy(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_01_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.3, self.1)
        }
    }
    #[inline]
    fn wz(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_10_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.3, self.2)
        }
    }
    #[inline]
    fn ww(self) -> Vec2 {
        #[cfg(vec4_sse2)]
        unsafe {
            Vec2::from(Vec4(_mm_shuffle_ps(self.0, self.0, 0b00_00_11_11)))
        }

        #[cfg(vec4_f32)]
        {
            Vec2(self.3, self.3)
        }
    }
}
