name: coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    strategy:
      fail-fast: false
      matrix:
        profile: [sse2_math, scalar_math, core_simd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo run --release -p ci -- coverage-llvm -p ${{ matrix.profile }} --lcov

      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: ${{ matrix.profile }}

  coverage-finalize:
    needs: [coverage]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Finalize coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
